Repository digiaonline/resourceplanningtool-ui, pull requests merged in 2018-04, with the labels that each got.

#17 Feature/add technology
  README.md
  src/project-view/components/ProjectView.css
  src/project-view/components/ProjectView.js
  src/projects-container/components/createTechnology.js
  src/projects-container/components/inputs.js
  src/projects-container/components/newsForm.js
  src/projects-container/components/projectModal.css
  src/projects-container/components/projectModal.js
  src/projects-container/form-config.js
  src/projects-container/projects-store.js
  src/projects-container/queries.js
Labels: wip

#36 add customer name display and fix duplication when submit project form
  src/project-view/components/ProjectView.js
  src/projects-container/form-config.js
Labels: bug

#35 remove html5 encode spacing and refine
  src/customer-view/components/CustomerView.css
  src/customer-view/components/CustomerView.js
  src/customers-container/components/CustomerForm.css
  src/customers-container/components/CustomersContainer.css
  src/customers-container/components/CustomersContainer.js
  src/people-container/components/PeopleContainer.css
  src/people-container/components/PeopleContainer.js
  src/people-container/components/PersonForm.css
  src/person-view/components/PersonView.css
  src/person-view/components/PersonView.js
  src/project-view/components/ProjectView.css
  src/projects-container/components/newsForm.js
  src/projects-container/components/projectModal.css
Labels: enhancement

#37 use default image for empty picture url
  src/assets/default-picture.png
  src/customer-view/components/CustomerView.js
  src/person-view/components/PersonView.js
  src/project-view/components/ProjectView.js
  src/projects-container/components/projects.js
Labels: enhancement

#40 fix newline in string parameter cause graphql request to fail
  src/constants/customer-form-config.js
  src/constants/person-form-config.js
  src/person-view/components/PersonView.css
  src/project-view/components/ProjectView.css
  src/project-view/components/ProjectView.js
  src/projects-container/components/projectModal.css
  src/projects-container/form-config.js
  src/utils/index.js
Labels: bug

#38 include display for customer's project list in customer view
  src/customer-view/components/CustomerView.css
  src/customer-view/components/CustomerView.js
  src/customers-container/customers-store.js
  src/customers-container/queries.js
Labels: enhancement

#48 Fix/ui issues
  src/customer-view/components/CustomerView.css
  src/customer-view/components/CustomerView.js
  src/header/components/Header.css
  src/person-view/components/PersonView.css
  src/person-view/components/PersonView.js
  src/project-view/components/ProjectView.css
  src/project-view/components/ProjectView.js
Labels: bug, enhancement
